@startuml

[*] --> 土状態センシング
土状態センシング : do 水センサーの取得
あさがおへのみずやり :GPIO 1
あさがおへのみずやり停止 : GPIO 0

土状態センシング -down-> あさがおへのみずやり:APIのレスポンス
あさがおへのみずやり -up-> 土状態センシング
土状態センシング -down-> あさがおへのみずやり停止:APIのレスポンス
あさがおへのみずやり停止 -up-> 土状態センシング

@enduml